[package]
name = "p3"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.11"
toml = "0.8"

# Image Handling
image = "0.25"
rawloader = "0.37"

# CLI
clap = { version = "4.5", features = [ "derive" ] }
